### PR TITLE
Don't go through the shell when running tar

### PR DESCRIPTION
**Pull request by pkkm**
Right now, `elpa-mirror` builds a tar command with `concat` and passes it to the shell. This will probably cause it to break when one of the paths contains spaces or special characters. We could wrap everything in `shell-quote-argument`, but it's simpler to just call tar directly from Emacs without launching an extra shell process. This pull request implements the change. I've also extracted the code to a separate function in order to be more confident that I won't break something while editing it.

### CODE REVIEW

**Comment by redguardtoo** [comment]
Thanks

**Comment by chen-bin-newscorp** [comment]
can you create a new pull request based on my latest code? `git rebase` on my master branch. Please also double check the `--format` option passed to `tar`. I think your original code has an error. Please not use macro which is a bit hard to read.

**Comment by redguardtoo** [comment]
can you create a new pull request based on my latest code? git rebase on my master branch. Please also double check the --format option passed to tar. I think your original code has an error. Please not use macro which is a bit hard to read.

**Comment by pkkm** [comment]
>Please also double check the --format option passed to tar. I think your original code has an error.

Right, looks like I've accidentally inverted the condition. Sorry for that.

>Please not use macro which is a bit hard to read.

Could you expand on what you mean? I haven't introduced any macro in this PR, just a function.

**Pull request merged**
