### PR TITLE
Some improvement.

### PR DESCRIPTION
**Pull request by tumashu**
1. defvar -> defcustom
2. Add elpamr-get-mirror-packages
3. elpamr-create-mirror-for-installed: add output-directory arg

### CODE REVIEW

**Comment by redguardtoo** [comment]
Thanks

**Comment by tumashu** [comment]
Haha, elpa-mirror is my emacs configure's core tool, I must make it better.

**Comment by ninrod** [comment]
it's a wonderful tool. @redguardtoo, thanks so much for this package.

**Comment by redguardtoo** [comment]
@ninrod Thank you for your compliments. ;)

**Pull request merged**
