### PR TITLE
elpamr-get-mirror-packages: use file-name-as-directory

### PR DESCRIPTION
**Pull request by tumashu**
Fix a possible bug.

### CODE REVIEW

**Comment by redguardtoo** [comment]
thanks

**Comment by tumashu** [comment]
I do not use at the moment, a possible usage is that we can use this feature to push mirror to github gh-pages

**Comment by tumashu** [comment]
一个粗糙的例子, 不过这个功能可能和重新自定义一个函数的工作量差不多.
```
(defun eh-elpamr-update (path)
  (shell-command
   (concat "cd " path " && "
           "git init &&"
           "git add -A && "
           "git commit -m \"comment\" && "
           "git push -f git@github.com:tumashu/test-elpa.git master")))

(add-hook 'elpamr-finished-hook 'eh-elpamr-update)

(elpamr-create-mirror-for-installed "~/test-elpa")

```

**Comment by redguardtoo** [comment]
Good. Now I understand.

**Comment by tumashu** [comment]
The below function seem to more simple :-)
```
  (defun eh-elpa-mirror-github ()
    (interactive)
    (let ((directory "~/.eh-elpa-mirror/"))
      (elpamr-create-mirror-for-installed directory t)
      (shell-command
       (concat "cd " directory " && "
               "git init &&"
               "git add -A && "
               "git commit -m \"Update elpa mirror\" && "
               "git push -f git@github.com:tumashu/elpa.git master &"))))
```

**Comment by tumashu** [comment]
maybe we should add a  elpamr-generate-mirror command,  user can set elpamr-mirror-url to a git remote repo. then run elpamr-generate-mirror, a personal elpa mirror will be generated.

**Comment by redguardtoo** [comment]
I prefer leaving it to users. Not everybody uses git. I do find dropbox is more reliable than github sometimes (through my office's firewall, for example)

**Comment by tumashu** [comment]
ok

**Pull request merged**
