### PR TITLE
Generalize the handling of paths and BSD tar

### PR DESCRIPTION
**Pull request by pkkm**
This is my proposed minor redesign of `elpa-mirror` with the goal to:
- Make it more predictable and easier to use for people who have `tar` or `cygpath` in an unusual place.
- Make it usable with any combination of operating system and tar variant, for example `bsdtar` on Linux.
- Improve performance.

The changes can be summarized as:
- Replace Windows executable finding logic with two `defcustom`s, `elpamr-tar-executable` and `elpamr-cygpath-executable`. This will force Windows users who have `tar` and `cygpath` in `C:\cygwin64\bin` or a similar location to add two lines to their `init.el` that they didn't need before. However, I still think this is overall the better solution, for two reasons. First, it lets `elpa-mirror` be used by people who have `tar` in an unusual location like `C:\Program Files (x86)\MSYS2\usr\bin` or `/home/pkkm/.bin`. Second, that's what users probably expect from other packages—for example, Magit uses a `magit-git-executable` variable.
- Don't use the shell unnecessarily.
- Check separately for macOS and BSD tar when each is relevant.
- Check for BSD tar only once per run of `elpamr-create-mirror-for-installed`.

Most of the changes also happen to improve performance. Here is the time it takes to recreate my repo at various commits, average of 100 runs:

| Commit | Time (s) |
| ---- | ---- |
| `master` |  1.74 |
| Remove unnecessary shell usage in elpamr--is-mac | 1.09 |
| Separate the check for BSD tar and the check for macOS | 0.90 |
| Check for BSD tar only once per run | 0.62 |

So this PR more than doubles the performance of `elpa-mirror` on my machine.

### CODE REVIEW

**Comment by redguardtoo** [comment]
Ok, could you rebase on master branch and squash the commit into one commit?

**Comment by pkkm** [comment]
OK!

**Comment by redguardtoo** [comment]
thanks

**Comment by redguardtoo** [comment]
Windows 10 user don't need set up tar location since tar is already part of system, right? I don't have Windows 10 right now.

**Comment by pkkm** [comment]
I don't have it either, but [this official article](https://techcommunity.microsoft.com/t5/containers/tar-and-curl-come-to-windows/ba-p/382409) says that Windows ships with bsdtar starting with an Insider Build from December 2017. So I think that everyone who uses Windows 10 from 2018 or later should have it.

**Comment by pkkm** [comment]
Thanks for creating this useful package, by the way!

**Pull request merged**
